FROM node:24-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm install

COPY . .

ENV  DATABASE_URL="postgresql://postgres:mysecretpassword@localhost:5432/postgres?schema=public&connection_limit=5&sslmode=disable"


RUN npx prisma migrate dev 
RUN npx prisma generate

EXPOSE 3000

CMD [ "npm" ,"start" ]

